name: my first workflow
on:
  workflow_dispatch:
jobs:
  hello:
    runs-on: arc-runner-set
    steps:
      - name: first step
        run: echo "hello world"
      - name: multiline
        run: |
          echo "first line"
          echo "second line"
      - name: setup java by action
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
  nextjob:
    runs-on: arc-runner-set
    needs: hello
    steps:
      - name: checkout code
        uses: actions/checkout@v4
